### ISSUE TITLE
Nuxt 3: Different private & public shopwareEndpoint runtime configs

### ISSUE THREAD

**Issue by AlexBa** [shopware/frontends#323]
### Description

I'm currently trying to set up Shopware frontends with Docker compose. While doing so I have noticed a problem with Nuxt 3: It doesn't work within Docker, because we need the Shopware endpoint runtime config to be more dynamic.

At the moment, there are basically two context in Nuxt 3: The server & client context. The problem is that the Shopware endpoint is different based on the context. In my case it's `http://localhost:8080` on the client and `http://shopware` on the server side.

This leads to the problem that the server side requests are failing. Here is my config:

docker-compose.yml
```
version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./apps/frontend
      args:
        NODE_VERSION: 18
    ports:
      - "80:3000"
      - "24678:24678"
    networks:
      - web
    environment:
      - SHOPWARE_ENDPOINT_PUBLIC=http://localhost:8080
      - SHOPWARE_ENDPOINT_PRIVATE=http://shopware
      - SHOPWARE_ACCESS_TOKEN=123456789
    volumes:
      - "./apps/frontend:/src"

  shopware:
    build:
      dockerfile: Dockerfile
      context: ./apps/shopware
    ports:
      - "8080:80"
      - "22:22"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - APP_URL=http://localhost
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.1
      - NODE_VERSION=18
    volumes:
      - "./apps/shopware:/var/www/html"
```

nuxt.config.ts
```
export default defineNuxtConfig({
  runtimeConfig: {
    shopware: {
      shopwareEndpoint: process.env.SHOPWARE_ENDPOINT_PRIVATE,
      shopwareAccessToken: process.env.SHOPWARE_ACCESS_TOKEN,
    },
    public: {
      shopware: {
        shopwareEndpoint: process.env.SHOPWARE_ENDPOINT_PUBLIC,
        shopwareAccessToken: process.env.SHOPWARE_ACCESS_TOKEN,
      },
    },
  },
})
```

The problem lies within `@shopware-pwa/nuxt3-module` in the `plugin.ts` file. As you can see, there is no distinction between the client & server context:
```
const instance = createInstance({
      endpoint: runtimeConfig.public.shopware.shopwareEndpoint,
      accessToken: runtimeConfig.public.shopware.shopwareAccessToken,
      timeout: runtimeConfig.public.shopware.shopwareAccessToken || 10000,
      auth: {
        username:
          "<%= options.shopwareApiClient.auth ? options.shopwareApiClient.auth.username : undefined %>",
        password:
          "<%=  options.shopwareApiClient.auth ? options.shopwareApiClient.auth.password : undefined %>",
      },
      contextToken: contextToken.value || cookieContextToken,
      languageId: languageId.value || cookieLanguageId,
    });
```

### Use Case

Docker setups are working again with Nuxt 3.

At the moment, only public Shopware shops (and thus public endpoints) are working.
